
"""Code-writing worker (o4-mini).

The WorkerAgent receives a single task plus additional context (plan,
repo summary, etc.) and must output a *single valid Python code block*
containing a patch that advances the repository toward the goal.

NOTE: At this stage the WorkerAgent is a thin wrapper around the existing
behaviour (identical contract to HeavyAgent) so it can be swapped into the
orchestration pipeline without disrupting tests.
"""
from __future__ import annotations
from typing import Dict, Any

from llm_helper import ask_o4


SYSTEM_PROMPT_TEMPLATE = """    You are a specialised CODE-WRITING worker agent.

Task: {task}

Additional context (JSON):
{context_json}

Reply with ONLY one Python code block that applies the change.
"""


def generate(task: str, context: Dict[str, Any]) -> str:
    """Return a Python patch block generated by o4-mini."""
    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(task=task, context_json=context)
    user_prompt = "Produce the patch now."
    return ask_o4(system_prompt, user_prompt)
